"use client";

import { useEffect, useState } from "react";
import { Timeline, type ClientArtifact } from "./Timeline";
import { ConversationSection } from "./ConversationSection";
import { SelfReflectionGate, type SelfReflection } from "./SelfReflection";
import type { Conversation, Insight } from "../lib/portfolio";

interface Props {
  studentName: string;
  artifacts: ClientArtifact[];
  kinds: { kind: string; label: string; count: number }[];
  insight: Insight;
  conversation: Conversation;
}

const STORAGE_KEY = "portfolio-self-reflection";

export function Portfolio({ studentName, artifacts, kinds, insight, conversation }: Props) {
  const firstName = studentName.split(" ")[0];

  // The student's first-pass reflection — their data, so it persists locally.
  const [reflection, setReflection] = useState<SelfReflection | null>(null);
  const [hydrated, setHydrated] = useState(false);

  useEffect(() => {
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      if (raw) setReflection(JSON.parse(raw) as SelfReflection);
    } catch {
      // ignore malformed storage
    }
    setHydrated(true);
  }, []);

  const commit = (r: SelfReflection) => {
    setReflection(r);
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(r));
    } catch {
      // ignore quota/availability errors — the gate still opens for this session
    }
  };

  const reopen = () => setReflection(null);

  return (
    <>
      {/* One shared artifact — the same page for {firstName} and their teacher. It opens
          with {firstName}'s own words, then unlocks the AI's read once they've written theirs. */}
      <div className="herowrap">
        <figure className="heroquote">
          <blockquote>“{insight.heroQuote.text}”</blockquote>
          <figcaption>— {firstName}, in “{insight.heroQuote.source}”</figcaption>
        </figure>
        <p className="student-intro">
          Everything {firstName} made this unit, in one place and in order — for {firstName} to look
          back on and for their teacher to read before the one-on-one. Scroll through to see the
          thinking, where the ideas changed, and who shows up across the work.
        </p>
      </div>

      {/* Autonomy hinge: the student diagnoses first; the AI responds to them. */}
      <SelfReflectionGate
        firstName={firstName}
        committed={reflection}
        onCommit={commit}
        onReopen={reopen}
      />
      {hydrated && reflection && (
        <InsightView insight={insight} firstName={firstName} reflection={reflection} />
      )}
      {hydrated && reflection && (
        <ConversationSection studentName={studentName} conversation={conversation} />
      )}

      <Timeline artifacts={artifacts} kinds={kinds} />
    </>
  );
}

function InsightView({
  insight,
  firstName,
  reflection,
}: {
  insight: Insight;
  firstName: string;
  reflection: SelfReflection;
}) {
  return (
    <section className="notice">
      {/* Divergence framing: the student's read next to the AI's, side by side. */}
      <div className="diverge">
        <span className="diverge-badge">Start the conversation here</span>
        <p className="diverge-lead">
          {firstName} wrote their own read first. Set it next to the AI&apos;s synthesis below —
          the most useful conversation, for {firstName} and their teacher alike, usually lives in
          the gap.
        </p>
        <div className="diverge-cols">
          <div className="diverge-col diverge-you">
            <span className="diverge-src">✎ {firstName}&apos;s own words</span>
            <p className="diverge-label">Their through-line</p>
            <p className="diverge-text">{reflection.throughLine}</p>
            <p className="diverge-label">Their top theme</p>
            <p className="diverge-text">{reflection.topTheme}</p>
          </div>
          <div className="diverge-col diverge-ai">
            <span className="diverge-src">✦ AI synthesis</span>
            <p className="diverge-label">Its through-line (in brief)</p>
            <p className="diverge-text">{insight.throughLine.split(". ")[0]}.</p>
            <p className="diverge-label">Its lead theme</p>
            <p className="diverge-text">{insight.themes[0]?.title}</p>
          </div>
        </div>
        <p className="diverge-prompt">
          Where do these two readings agree? Where do they diverge? That gap is the first thing
          worth talking through together.
        </p>
      </div>

      <div className="notice-lead">
        <span className="ai-badge">✦ Full AI synthesis of all {firstName}&apos;s work</span>
        <p className="notice-hint">
          Generated by reading the full portfolio, revealed only after {firstName}&apos;s own read.
          Every observation is tied to evidence from the work below — so it can be questioned, not
          just accepted.
        </p>
      </div>

      {/* Questions first — the headline output */}
      <div className="block block-questions">
        <h2>Questions to open with</h2>
        <ol className="qlist">
          {insight.questions.map((q, i) => (
            <li key={i}>
              <p className="q-text">{q.question}</p>
              <p className="q-why">{q.rationale}</p>
            </li>
          ))}
        </ol>
      </div>

      <div className="block">
        <h2>The through-line</h2>
        <p className="throughline">{insight.throughLine}</p>
      </div>

      <div className="block">
        <h2>Emerging themes</h2>
        <div className="themes">
          {insight.themes.map((t, i) => (
            <div className="theme" key={i}>
              <h3>{t.title}</h3>
              <p className="theme-sum">{t.summary}</p>
              <ul className="theme-ev">
                {t.evidence.map((e, j) => (
                  <li key={j}>
                    <span className="ev-quote">“{e.quote}”</span>
                    <span className="ev-src">{e.source}</span>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </div>

      <div className="two-col">
        <div className="block">
          <h2 className="h-thrive">Where {firstName}&apos;s thriving</h2>
          <ul className="pointlist">
            {insight.thriving.map((p, i) => (
              <li key={i}>
                <span className="pt-point">{p.point}</span>
                <span className="pt-ev">{p.evidence}</span>
              </li>
            ))}
          </ul>
        </div>
        <div className="block">
          <h2 className="h-watch">Gentle watch-fors</h2>
          <ul className="pointlist">
            {insight.watchFors.map((p, i) => (
              <li key={i}>
                <span className="pt-point">{p.point}</span>
                <span className="pt-ev">{p.evidence}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </section>
  );
}
